#!/usr/bin/env bash
# This script manages manage_my_process with start, stop and restart
pid_file="/var/run/my_process.pid"
case "$1" in
	start)
		./manage_my_process &
		echo "$!" > "$pid_file"
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat "$pid_file")"
		rm -f "$pid_file"
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat "$pid_file")"
		rm -f "$pid_file"
		./manage_my_process &
		echo "$!" > "$pid_file"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
